name: Run tests
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Run Java tests
        working-directory: ./api/junit5-migration-maven
        run: ./mvnw verify
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./ui/react-testing-library
        run: npm install

      - name: Run Jest tests
        working-directory: ./ui/react-testing-library
        run: npm test

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages/allure-reports/${{ github.event.pull_request.number }}

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.10
        if: always()
        with:
          gh_pages: gh-pages/allure-reports/${{ github.event.pull_request.number }}
          allure_history: gh-pages/allure-reports/${{ github.event.pull_request.number }}/allure-history
          allure_results: allure-results
      
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages/allure-reports/${{ github.event.pull_request.number }}/allure-history
          destination_dir: allure-reports/${{ github.event.pull_request.number }}