name: Generate Allure Report

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID service parameter. Leave blank
      ALLURE_USERNAME:
        description: ALLURE_USERNAME service parameter. Leave blank

env:
  ALLURE_ENDPOINT: https://reportstest.testops.cloud/
  ALLURE_PROJECT_ID: 1
  ALLURE_TOKEN: ${{ secrets.ALLURE_TESTOPS_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: ../../allure-results
  ALLURE_LAUNCH_TAGS: ${{ github.repository }}, branch-${{ github.head_ref }}, pr-${{ github.event.number }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
            distribution: zulu
            java-version: '17'
            
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
          
      - name: Run Java tests
        working-directory: ./api/junit5-migration-maven
        run: allurectl watch -- ./mvnw verify
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./ui/react-testing-library
        run: npm install

      - name: Run Jest tests
        working-directory: ./ui/react-testing-library
        run: allurectl watch -- npm test |
          echo "ALLURE_JOB_RUN_URL=$(allurectl job-run env | grep ALLURE_JOB_RUN_URL)" >> $GITHUB_ENV
          
      - name: Comment PR with Allure Report link
        if: ${{ always() && github.event_name == 'pull_request' }}
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🎉 Allure Report is ready: [View Report](${{ env.ALLURE_JOB_RUN_URL }})
          comment_tag: allure_report
          mode: recreate
